### ISSUE TITLE
[Feat] 단어 추가 View UI 구현

### ISSUE THREAD

**Issue by kingjeongkong** [SOPKATHON-iOS-TEAM4/iOS#16]
## 🛠 Issue

단어 추가 View UI 구현

## 📝 To-do

- [x] 단어 UILabel
- [x] 영단어 입력 TextField
- [x] 영단어 입력 TextField 내의 추가하기 Button
- [x] 영단어 뜻 입력 TextField
- [x] 영단어 뜻 입력 TextField 내의 추가하기 Button
- [x] 글자 수 UILabel 
- [x] 추가된 단어 History (UICollectionView)
- [x] 확인 Button
